base_statline = {
    "Amazon_Thrower":"6337",
    "Dark Elf_Runner":"7347",
    "High Elf_Thrower":"6348",
    "Human_Thrower":"6338",
    "Norse_Thrower":"6337",
    "Pro Elf_Thrower":"6347",
    "Skaven_Thrower":"7337",
    "Underworld_Thrower":"7337",
    "Wood Elf_Thrower":"7347",
    "Amazon_Catcher":"6337",
    "Bretonnian_Blitzer":"7338",
    "Dark Elf_Witch Elf":"7347",
    "Dwarf_Runner":"6338",
    "Goblin_Goblin":"6237S",
    "Goblin_Pogoer":"7237S",
    "Halfling_Halfling":"5236S",
    "High Elf_Catcher":"8347",
    "Human_Catcher":"8237",
    "Khemri_ThroRa":"6327",
    "Kislev_Catcher":"7247",
    "Necromantic_Werewolf":"8338",
    "Norse_Runner":"7337",
    "Orc_Goblin":"6237S",
    "Orc_Thrower":"5338",
    "Pro Elf_Catcher":"8347",
    "Skaven_Gutter Runner":"9247",
    "Lizardman_Skink":"8237S",
    "Undead_Ghoul":"7337",
    "Underworld_Goblin":"6237S",
    "Vampire_Vampire":"6448",
    "Wood Elf_Catcher":"8247",
    "Amazon_Blitzer":"6337",
    "Amazon_Linewoman":"6337",
    "Nurgle_BeastOfNurgle":"4519",
    "Orc_BlackOrcBlocker":"4429",
    "Chaos Dwarf_Minotaur":"5528",
    "Chaos_Warrior":"5439",
    "Dwarf_DeathRoller":"471a",
    "Goblin_Troll":"4519",
    "Halfling_Treeman":"261a",
    "Human_Ogre":"5529",
    "Khemri_Tomb Guardian":"4519",
    "Kislev_Tame Bear":"6519",
    "Lizardman_Kroxigor":"6519",
    "Chaos_Minotaur":"5528",
    "Necromantic_Flesh Golem":"4429",
    "Norse_Ulfwerener":"6428",
    "Norse_Yhetee":"5518",
    "Nurgle_Pestigor":"6338",
    "Nurgle_NurgleWarrior":"4429",
    "Ogre_Ogre":"5529",
    "Orc_Troll":"4519",
    "Lizardman_Saurus":"6419",
    "Skaven_Rat Ogre":"6528",
    "Undead_Mummy":"3519",
    "Underworld_Troll":"4519",
    "Wood Elf_Treeman":"261a",
    "Chaos Dwarf_Bull Centaur":"6429",
    "Bretonnian_Blocker":"6338",
    "Bretonnian_Lineman":"6327",
    "Chaos_Beastman":"6338",
    "Chaos Dwarf_Blocker":"4329",
    "Chaos Dwarf_Hobgoblin":"6337",
    "Skaven_Blitzer":"7338",
    "Underworld_Blitzer":"7338",
    "Dark Elf_Assassin":"6347",
    "Dark Elf_Blitzer":"7348",
    "Dark Elf_Lineman":"6348",
    "Goblin_Looney":"6237S",
    "Human_Lineman":"6338",
    "Khemri_Skeleton":"5327",
    "Norse_Lineman":"6337",
    "Nurgle_Rotter":"5338",
    "Ogre_Gnoblar":"5135S",
    "Orc_Lineman":"5339",
    "Skaven_Lineman":"7337",
    "Vampire_Thrall":"6337",
    "Undead_Skeleton":"5327",
    "Undead_Zombie":"4328",
    "Underworld_Lineman":"7337",
    "High Elf_Lineman":"6348",
    "Pro Elf_Lineman":"6347",
    "Wood Elf_Lineman":"7347",
    "Dwarf_Blitzer":"5339",
    "Dwarf_Blocker":"4329",
    "Dwarf_Troll Slayer":"5328",
    "High Elf_Blitzer":"7348",
    "Pro Elf_Blitzer":"7348",
    "Goblin_Bombardier":"6237S",
    "Goblin_Fanatic":"3737S",
    "Human_Blitzer":"7338",
    "Kislev_Blitzer":"7338",
    "Kislev_Lineman":"6338",
    "Orc_Blitzer":"6339",
    "Undead_Wight":"6338",
    "Norse_Berserker":"6337",
    "Khemri_BlitzRa":"6238",
    "Wood Elf_Wardancer":"8347",
    "Human/Ogre_Ogre":"5529",
    "Necromantic_Zombie":"4328",
    "Human/Bretonnian_Lineman":"6338",
    "Khemri/Undead_Skeleton":"5327",
    "Lizardman/Kislev_Kroxigor":"6519",
    "Orc/Goblin_Goblin":"6237S",
    "Orc/Goblin_Troll":"4519",
    "Skaven/Underworld_Lineman":"7337",
    "Skaven/Underworld_Storm Vermin":"7338",
    "Chaos/Chaos Dwarf_Minotaur":"5528",
    "Human/Norse/Kislev/Bretonnian_Lineman":"6338",
    "Chaos/Nurgle_Beastman/Pestigor":"6338",
}

base_skills = {
    "Amazon_Thrower":"Dodge,Pass",
    "Dark Elf_Runner":"Dump-Off",
    "High Elf_Thrower":"Pass,Safe Throw",
    "Human_Thrower":"Sure Hands,Pass",
    "Norse_Thrower":"Block,Pass",
    "Pro Elf_Thrower":"Pass",
    "Skaven_Thrower":"Sure Hands,Pass",
    "Underworld_Thrower":"Animosity,Sure Hands,Pass",
    "Wood Elf_Thrower":"Pass",
    "Amazon_Catcher":"Dodge,Catch",
    "Bretonnian_Blitzer":"Block,Dauntless,Catch",
    "Dark Elf_Witch Elf":"Dodge,Jump Up,Frenzy",
    "Dwarf_Runner":"Sure Hands,Thick Skull",
    "Goblin_Goblin":"Stunty,Dodge,Right Stuff",
    "Goblin_Pogoer":"Stunty,Dodge,Very Long Legs,Leap",
    "Halfling_Halfling":"Stunty,Dodge,Right Stuff",
    "High Elf_Catcher":"Catch",
    "Human_Catcher":"Dodge,Catch",
    "Khemri_ThroRa":"Sure Hands,Pass,Regeneration",
    "Kislev_Catcher":"Leap,Very Long Legs,Diving Catch",
    "Necromantic_Werewolf":"Claw,Regeneration,Frenzy",
    "Norse_Runner":"Block,Dauntless",
    "Orc_Goblin":"Stunty,Dodge,Right Stuff",
    "Orc_Thrower":"Sure Hands,Pass",
    "Pro Elf_Catcher":"Nerves of Steel,Catch",
    "Skaven_Gutter Runner":"Dodge",
    "Lizardman_Skink":"Stunty,Dodge",
    "Undead_Ghoul":"Dodge",
    "Underworld_Goblin":"Stunty,Dodge,Right Stuff",
    "Vampire_Vampire":"Blood Lust,Hypnotic Gaze,Regeneration",
    "Wood Elf_Catcher":"Catch,Dodge,Sprint",
    "Amazon_Blitzer":"Dodge,Block",
    "Amazon_Linewoman":"Dodge",
    "Nurgle_BeastOfNurgle":"Really Stupid,Regeneration,Nurgles Rot,Tentacles,Mighty Blow,Foul Appearance,Disturbing Presence,Loner",
    "Orc_BlackOrcBlocker":"",
    "Chaos Dwarf_Minotaur":"Wild Animal,Horns,Frenzy,Thick Skull,Mighty Blow,Loner",
    "Chaos_Warrior":"",
    "Dwarf_DeathRoller":"Break Tackle,Dirty Player,Juggernaut,Loner,Mighty Blow,No Hands,Secret Weapon,Stand Firm",
    "Goblin_Troll":"Really Stupid,Throw Team-Mate,Always Hungry,Regeneration,Mighty Blow,Loner",
    "Halfling_Treeman":"Take Root,Mighty Blow,Stand Firm,Strong Arm,Thick Skull,Throw Team-Mate",
    "Human_Ogre":"Bone-Head,Throw Team-Mate,Thick Skull,Mighty Blow,Loner",
    "Khemri_Tomb Guardian":"Decay,Regeneration",
    "Kislev_Tame Bear":"Bone-Head,Prehensile Tail,Thick Skull,Mighty Blow,Loner",
    "Lizardman_Kroxigor":"Bone-Head,Prehensile Tail,Thick Skull,Mighty Blow,Loner",
    "Chaos_Minotaur":"Wild Animal,Horns,Frenzy,Thick Skull,Mighty Blow,Loner",
    "Necromantic_Flesh Golem":"Regeneration,Thick Skull,Stand Firm",
    "Norse_Ulfwerener":"Frenzy",
    "Norse_Yhetee":"Wild Animal,Disturbing Presence,Frenzy,Claw,Loner",
    "Nurgle_Pestigor":"Regeneration,Nurgles Rot,Horns",
    "Nurgle_NurgleWarrior":"Regeneration,Nurgles Rot,Disturbing Presence,Foul Appearance",
    "Ogre_Ogre":"Bone-Head,Throw Team-Mate,Thick Skull,Mighty Blow",
    "Orc_Troll":"Really Stupid,Throw Team-Mate,Always Hungry,Regeneration,Mighty Blow,Loner",
    "Lizardman_Saurus":"",
    "Skaven_Rat Ogre":"Wild Animal,Frenzy,Prehensile Tail,Mighty Blow,Loner",
    "Undead_Mummy":"Mighty Blow,Regeneration",
    "Underworld_Troll":"Really Stupid,Throw Team-Mate,Always Hungry,Regeneration,Mighty Blow,Loner",
    "Wood Elf_Treeman":"Take Root,Mighty Blow,Strong Arm,Stand Firm,Thick Skull,Throw Team-Mate,Loner",
    "Chaos Dwarf_Bull Centaur":"Thick Skull,Sprint,Sure Feet",
    "Bretonnian_Blocker":"Wrestle",
    "Bretonnian_Lineman":"Fend",
    "Chaos_Beastman":"Horns",
    "Chaos Dwarf_Blocker":"Block,Thick Skull,Tackle",
    "Chaos Dwarf_Hobgoblin":"",
    "Skaven_Blitzer":"Block",
    "Underworld_Blitzer":"Animosity,Block",
    "Dark Elf_Assassin":"Shadowing,Stab",
    "Dark Elf_Blitzer":"Block",
    "Dark Elf_Lineman":"",
    "Goblin_Looney":"Stunty,Chainsaw,Secret Weapon",
    "Human_Lineman":"",
    "Khemri_Skeleton":"Regeneration,Thick Skull",
    "Norse_Lineman":"Block",
    "Nurgle_Rotter":"Decay,Nurgles Rot",
    "Ogre_Gnoblar":"Stunty,Titchy,Dodge,Sidestep,Right Stuff",
    "Orc_Lineman":"",
    "Skaven_Lineman":"",
    "Vampire_Thrall":"",
    "Undead_Skeleton":"Regeneration,Thick Skull",
    "Undead_Zombie":"Regeneration",
    "Underworld_Lineman":"Animosity",
    "High Elf_Lineman":"",
    "Pro Elf_Lineman":"",
    "Wood Elf_Lineman":"",
    "Dwarf_Blitzer":"Block,Thick Skull",
    "Dwarf_Blocker":"Block,Thick Skull,Tackle",
    "Dwarf_Troll Slayer":"Block,Thick Skull,Frenzy,Dauntless",
    "High Elf_Blitzer":"Block",
    "Pro Elf_Blitzer":"Block,Sidestep",
    "Goblin_Bombardier":"Stunty,Bombardier,Dodge,Secret Weapon",
    "Goblin_Fanatic":"Ball Chain,No Hands,Secret Weapon,Stunty",
    "Human_Blitzer":"Block",
    "Kislev_Blitzer":"Leap,Very Long Legs,Jump Up,Diving Tackle",
    "Kislev_Lineman":"Leap,Very Long Legs",
    "Orc_Blitzer":"Block",
    "Undead_Wight":"Block,Regeneration",
    "Norse_Berserker":"Block,Frenzy,Jump Up",
    "Khemri_BlitzRa":"Block,Regeneration",
    "Wood Elf_Wardancer":"Block,Dodge,Leap",
    "Human/Ogre_Ogre":"Bone-Head,Throw Team-Mate,Thick Skull,Mighty Blow",
    "Necromantic_Zombie":"Regeneration",
    "Human/Bretonnian_Lineman":"",
    "Khemri/Undead_Skeleton":"Thick Skull,Regeneration",
    "Lizardman/Kislev_Kroxigor":"Bone-Head,Prehensile Tail,Thick Skull,Mighty Blow,Loner",
    "Orc/Goblin_Goblin":"Stunty,Dodge,Right Stuff",
    "Orc/Goblin_Troll":"Really Stupid,Throw Team-Mate,Always Hungry,Regeneration,Mighty Blow,Loner",
    "Skaven/Underworld_Lineman":"",
    "Skaven/Underworld_Storm Vermin":"Block",
    "Chaos/Chaos Dwarf_Minotaur":"Wild Animal,Horns,Frenzy,Thick Skull,Mighty Blow,Loner",
    "Human/Norse/Kislev/Bretonnian_Lineman":"",
    "Chaos/Nurgle_Beastman/Pestigor":"Horns",
}

mutation_positionals = [
    "Skaven_Thrower", "Underworld_Thrower", "Skaven_Gutter Runner",
    "Underworld_Goblin", "Nurgle_BeastOfNurgle",
    "Chaos Dwarf_Minotaur", "Chaos_Warrior",
    "Chaos_Minotaur", "Nurgle_Pestigor",
    "Nurgle_NurgleWarrior", "Skaven_Rat Ogre",
    "Underworld_Troll", "Chaos_Beastman",
    "Chaos Dwarf_Blocker", "Nurgle_Rotter",
    "Skaven_Blitzer", "Underworld_Blitzer",
    "Skaven_Lineman", "Underworld_Lineman",
    "Skaven/Underworld_Lineman",
    "Skaven/Underworld_Storm Vermin",
    "Chaos/Chaos Dwarf_Minotaur",
    "Chaos/Nurgle_Beastman/Pestigor",
]