"""empty message

Revision ID: 08d3032205b0
Revises: 9e46be2d1f74
Create Date: 2019-08-30 17:27:30.847994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d3032205b0'
down_revision = '9e46be2d1f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_templates', sa.Column('position', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_templates', 'position')
    # ### end Alembic commands ###
