"""empty message

Revision ID: 0f66ab5ff629
Revises: 08d3032205b0
Create Date: 2019-12-07 08:56:22.824530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f66ab5ff629'
down_revision = '08d3032205b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cracker_card_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('race', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('klass', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=30), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('one_time_use', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('built_in_skill', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cracker_card_templates_card_type'), 'cracker_card_templates', ['card_type'], unique=False)
    op.create_index(op.f('ix_cracker_card_templates_name'), 'cracker_card_templates', ['name'], unique=False)
    op.create_index(op.f('ix_cracker_card_templates_rarity'), 'cracker_card_templates', ['rarity'], unique=False)
    op.create_table('cracker_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('coach', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cracker_team_coach'), 'cracker_team', ['coach'], unique=False)
    op.create_table('cracker_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['cracker_team.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['cracker_card_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cracker_cards_team_id'), 'cracker_cards', ['team_id'], unique=False)
    op.create_index(op.f('ix_cracker_cards_template_id'), 'cracker_cards', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_cracker_cards_template_id'), table_name='cracker_cards')
    #op.drop_index(op.f('ix_cracker_cards_team_id'), table_name='cracker_cards')
    op.drop_table('cracker_cards')
    op.drop_index(op.f('ix_cracker_team_coach'), table_name='cracker_team')
    op.drop_table('cracker_team')
    op.drop_index(op.f('ix_cracker_card_templates_rarity'), table_name='cracker_card_templates')
    op.drop_index(op.f('ix_cracker_card_templates_name'), table_name='cracker_card_templates')
    op.drop_index(op.f('ix_cracker_card_templates_card_type'), table_name='cracker_card_templates')
    op.drop_table('cracker_card_templates')
    # ### end Alembic commands ###
