"""empty message

Revision ID: 21cc16de7963
Revises: a69f48e77a9d
Create Date: 2020-05-29 12:56:47.716091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cc16de7963'
down_revision = 'a69f48e77a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('conclave_triggered', sa.Boolean(), nullable=False,server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'conclave_triggered')
    # ### end Alembic commands ###
