"""empty message

Revision ID: 259070ac705a
Revises: 96400e7b07b1
Create Date: 2020-03-05 11:11:23.032542

"""
from alembic import op
import sqlalchemy as sa
from models.data_models import TextPickleType

# revision identifiers, used by Alembic.
revision = '259070ac705a'
down_revision = '96400e7b07b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('disabled_cards', TextPickleType(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'disabled_cards')
    # ### end Alembic commands ###
