"""empty message

Revision ID: 2edd410e2512
Revises: e1d5821bcf50
Create Date: 2019-05-09 20:28:39.821446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2edd410e2512'
down_revision = 'e1d5821bcf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('in_development_deck', sa.Boolean(), nullable=True, server_default=sa.text("'0'")))
    op.add_column('cards', sa.Column('in_imperium_deck', sa.Boolean(), nullable=True, server_default=sa.text("'0'")))
    op.add_column('packs', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.alter_column('packs', 'coach_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key("packs_deck_key", 'packs', 'decks', ['deck_id'], ['id'])
    op.add_column('tournaments', sa.Column('phase', sa.String(length=255), nullable=False,server_default=sa.text("'team_building'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'phase')
    op.drop_constraint("packs_deck_key", 'packs', type_='foreignkey')
    op.alter_column('packs', 'coach_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('packs', 'deck_id')
    op.drop_column('cards', 'in_imperium_deck')
    op.drop_column('cards', 'in_development_deck')
    # ### end Alembic commands ###
