"""empty message

Revision ID: 31fead39d1e5
Revises: 4979e92f2e67
Create Date: 2020-01-09 16:05:21.813863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31fead39d1e5'
down_revision = '4979e92f2e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_templates', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_templates', sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###
