"""empty message

Revision ID: 42f93c2a1f8f
Revises: 5eda83f88337
Create Date: 2020-02-07 10:22:36.780077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f93c2a1f8f'
down_revision = '5eda83f88337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_rooms', sa.Column('region', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_rooms', 'region')
    # ### end Alembic commands ###
