"""empty message

Revision ID: 470006fe6087
Revises: c211662eaf4a
Create Date: 2019-04-15 12:08:36.262294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470006fe6087'
down_revision = 'c211662eaf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discord_channel', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=80), nullable=False),
    sa.Column('signup_close_date', sa.String(length=80), nullable=True),
    sa.Column('expected_start_date', sa.String(length=80), nullable=True),
    sa.Column('expected_end_date', sa.String(length=80), nullable=True),
    sa.Column('deadline_date', sa.String(length=80), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('coach_limit', sa.Integer(), nullable=False),
    sa.Column('reserve_limit', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('deck_limit', sa.Integer(), nullable=False),
    sa.Column('admin', sa.String(length=80), nullable=True),
    sa.Column('sponsor', sa.String(length=80), nullable=True),
    sa.Column('special_rules', sa.Text(), nullable=True),
    sa.Column('prizes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_tournament_id'), 'tournaments', ['tournament_id'], unique=True)
    op.create_table('tournaments_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'coach_id', name='uix_tournament_id_coach_id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_coaches_name'), 'coaches', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaches_name'), table_name='coaches')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('tournaments_signups')
    op.drop_index(op.f('ix_tournaments_tournament_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
