"""empty message

Revision ID: 495f6089303a
Revises: 6079b8e71c44
Create Date: 2019-04-27 12:33:04.468211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '495f6089303a'
down_revision = '6079b8e71c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('disc_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_coaches_disc_id'), 'coaches', ['disc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaches_disc_id'), table_name='coaches')
    op.drop_column('coaches', 'disc_id')
    # ### end Alembic commands ###
