"""empty message

Revision ID: 4979e92f2e67
Revises: 0f66ab5ff629
Create Date: 2020-01-07 09:50:20.163205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4979e92f2e67'
down_revision = '0f66ab5ff629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('coach_limit', sa.Integer(), nullable=False),
    sa.Column('deck_limit', sa.Integer(), nullable=False),
    sa.Column('deck_value_limit', sa.Integer(), nullable=False),
    sa.Column('prizes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cracker_cards_pack_id'), 'cracker_cards', ['pack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cracker_cards_pack_id'), table_name='cracker_cards')
    op.drop_table('tournament_templates')
    # ### end Alembic commands ###
