"""empty message

Revision ID: 551e7f9786f5
Revises: f7fe8c9cf8e6
Create Date: 2019-05-31 09:39:44.452685

"""
from alembic import op
import sqlalchemy as sa
from models.data_models import TextPickleType


# revision identifiers, used by Alembic.
revision = '551e7f9786f5'
down_revision = 'f7fe8c9cf8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('achievements', TextPickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'achievements')
    # ### end Alembic commands ###
