"""empty message

Revision ID: 56b998f0fadf
Revises: 259070ac705a
Create Date: 2020-04-13 10:53:24.859200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b998f0fadf'
down_revision = '259070ac705a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('super_admin', sa.Boolean(), nullable=True, server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'super_admin')
    # ### end Alembic commands ###
