"""empty message

Revision ID: 590a8b5ca5d9
Revises: b70dbe7f71c2
Create Date: 2019-08-10 21:15:23.410615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '590a8b5ca5d9'
down_revision = 'b70dbe7f71c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='coaches')
    op.add_column('transactions', sa.Column('season', sa.String(length=20), nullable=False, server_default=sa.schema.DefaultClause("1")))
    op.alter_column('transactions', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_transactions_season'), 'transactions', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_season'), table_name='transactions')
    op.alter_column('transactions', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('transactions', 'season')
    op.create_index('name', 'coaches', ['name'], unique=True)
    # ### end Alembic commands ###
