"""empty message

Revision ID: 5eda83f88337
Revises: d004fdd46834
Create Date: 2020-01-29 19:45:42.588062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eda83f88337'
down_revision = 'd004fdd46834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('conclave_triggered', sa.Boolean(), nullable=False,server_default=sa.text("'0'")))
    op.add_column('tournaments', sa.Column('conclave_triggers', sa.Text(), nullable=True))
    op.drop_column('tournaments', 'consecration')
    op.drop_column('tournaments', 'corruption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('corruption', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('tournaments', sa.Column('consecration', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('tournaments', 'conclave_triggers')
    op.drop_column('tournaments', 'conclave_triggered')
    # ### end Alembic commands ###
