"""empty message

Revision ID: 6079b8e71c44
Revises: c899fcc20fe3
Create Date: 2019-04-21 18:37:30.217152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6079b8e71c44'
down_revision = 'c899fcc20fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id')
    )
    op.add_column('cards', sa.Column('duster_id', sa.Integer(), nullable=True))
    op.create_foreign_key('cards_duster_key', 'cards', 'dusters', ['duster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_duster_key', 'cards', type_='foreignkey')
    op.drop_column('cards', 'duster_id')
    op.drop_table('dusters')
    # ### end Alembic commands ###
