"""empty message

Revision ID: 6de92613a975
Revises: 36d7a8641fd1
Create Date: 2020-06-04 20:20:03.534115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de92613a975'
down_revision = '36d7a8641fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_command_squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('high_command_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['high_command_id'], ['high_commands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('squad_cards',
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['high_command_squads.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squad_cards')
    op.drop_table('high_command_squads')
    # ### end Alembic commands ###
