"""empty message

Revision ID: 73133c8f8ab4
Revises: 6de92613a975
Create Date: 2020-06-06 19:31:50.046034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73133c8f8ab4'
down_revision = '6de92613a975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('uses', sa.Integer(), nullable=False, server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'uses')
    # ### end Alembic commands ###
