"""empty message

Revision ID: 75d9f001bbfa
Revises: 495f6089303a
Create Date: 2019-05-05 20:17:56.774127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75d9f001bbfa'
down_revision = '495f6089303a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('web_admin', sa.Boolean(), nullable=True, server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'web_admin')
    # ### end Alembic commands ###
