"""empty message

Revision ID: 7c08c1236d17
Revises: 5a9322e77fc2
Create Date: 2019-05-22 08:25:16.635791

"""
from alembic import op
import sqlalchemy as sa
from models.data_models import TextPickleType


# revision identifiers, used by Alembic.
revision = '7c08c1236d17'
down_revision = '5a9322e77fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('assigned_to_array', TextPickleType(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'assigned_to_array')
    # ### end Alembic commands ###
