"""empty message

Revision ID: 840ddc54e942
Revises: dfac7c5c01fb
Create Date: 2020-01-29 09:40:20.607076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840ddc54e942'
down_revision = 'dfac7c5c01fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conclave_rules', sa.Column('level1_description', sa.Text(), nullable=False))
    op.add_column('conclave_rules', sa.Column('level2_description', sa.Text(), nullable=False))
    op.add_column('conclave_rules', sa.Column('level3_description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conclave_rules', 'level3_description')
    op.drop_column('conclave_rules', 'level2_description')
    op.drop_column('conclave_rules', 'level1_description')
    # ### end Alembic commands ###
