"""empty message

Revision ID: 9116284b0940
Revises: c211662eaf4a
Create Date: 2019-04-13 19:29:26.846436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9116284b0940'
down_revision = 'c211662eaf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=80), nullable=False),
    sa.Column('signup_close_date', sa.String(length=80), nullable=False),
    sa.Column('expected_start_date', sa.String(length=80), nullable=False),
    sa.Column('expected_end_date', sa.String(length=80), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('coach_limit', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('deck_limit', sa.Integer(), nullable=True),
    sa.Column('admin', sa.String(length=80), nullable=True),
    sa.Column('sponsor', sa.String(length=80), nullable=False),
    sa.Column('special_rules', sa.Text(), nullable=True),
    sa.Column('prizes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_tournament_id'), 'tournaments', ['tournament_id'], unique=True)
    op.create_table('tournaments_signups',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments_signups')
    op.drop_index(op.f('ix_tournaments_tournament_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
