"""empty message

Revision ID: 96400e7b07b1
Revises: 42f93c2a1f8f
Create Date: 2020-02-15 08:26:18.669605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96400e7b07b1'
down_revision = '42f93c2a1f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=80), nullable=False),
    sa.Column('competition_type', sa.String(length=80), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('turn_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp_id')
    )
    op.create_index(op.f('ix_competitions_league_id'), 'competitions', ['league_id'], unique=False)
    op.create_index(op.f('ix_competitions_league_name'), 'competitions', ['league_name'], unique=False)
    op.create_index(op.f('ix_competitions_name'), 'competitions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitions_name'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_league_name'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_league_id'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
