"""empty message

Revision ID: 9bed2071be9f
Revises: a015feaa7e24
Create Date: 2019-07-26 14:24:34.226609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bed2071be9f'
down_revision = 'a015feaa7e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_template_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cards_card_template_id'), 'cards', ['card_template_id'], unique=False)
    op.create_foreign_key("cards_card_templates_key", 'cards', 'card_templates', ['card_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("cards_card_templates_key", 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_card_template_id'), table_name='cards')
    op.drop_column('cards', 'card_template_id')
    # ### end Alembic commands ###
