"""empty message

Revision ID: 9e46be2d1f74
Revises: 590a8b5ca5d9
Create Date: 2019-08-26 10:55:19.934301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e46be2d1f74'
down_revision = '590a8b5ca5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('deck_value_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'deck_value_limit')
    # ### end Alembic commands ###
