"""empty message

Revision ID: a69f48e77a9d
Revises: de895e87060c
Create Date: 2020-05-28 17:47:24.930883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69f48e77a9d'
down_revision = 'de895e87060c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_templates', sa.Column('conclave_distance', sa.Integer(), nullable=False))
    op.add_column('tournament_templates', sa.Column('deck_value_target', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_templates', 'deck_value_target')
    op.drop_column('tournament_templates', 'conclave_distance')
    # ### end Alembic commands ###
