"""empty message

Revision ID: b449e840fbc6
Revises: 56b998f0fadf
Create Date: 2020-05-25 17:13:13.388919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b449e840fbc6'
down_revision = '56b998f0fadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('banned_cards', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'banned_cards')
    # ### end Alembic commands ###
