"""empty message

Revision ID: b70dbe7f71c2
Revises: ffaa3bbd24a0
Create Date: 2019-08-06 21:06:57.697121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70dbe7f71c2'
down_revision = 'ffaa3bbd24a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_templates', sa.Column('one_time_use', sa.Boolean(), nullable=False, server_default=sa.schema.DefaultClause("0")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_templates', 'one_time_use')
    # ### end Alembic commands ###
