"""empty message

Revision ID: ba0330bb1335
Revises: fbbcc3045320
Create Date: 2019-06-16 09:33:58.639473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0330bb1335'
down_revision = 'fbbcc3045320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('skill_access', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'skill_access')
    # ### end Alembic commands ###
