"""empty message

Revision ID: be1d39187a0f
Revises: 75d9f001bbfa
Create Date: 2019-05-07 09:00:33.409686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1d39187a0f'
down_revision = '75d9f001bbfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('value', sa.Integer(), nullable=False, server_default=sa.text("'1'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'value')
    # ### end Alembic commands ###
