"""empty message

Revision ID: c5223054be86
Revises: be1d39187a0f
Create Date: 2019-05-11 19:24:27.889245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from models.data_models import TextPickleType

# revision identifiers, used by Alembic.
revision = 'c5223054be86'
down_revision = 'be1d39187a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('mixed_team', sa.String(length=255), nullable=False),
    sa.Column('commited', sa.Boolean(), nullable=True),
    sa.Column('extra_cards', TextPickleType(), nullable=False),
    sa.Column('unused_extra_cards', TextPickleType(), nullable=False),
    sa.Column('starter_cards', TextPickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], )
    )
    op.add_column('cards', sa.Column('in_development_deck', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('in_imperium_deck', sa.Boolean(), nullable=True))
    op.add_column('tournaments', sa.Column('phase', sa.String(length=255), nullable=False))
    op.add_column('tournaments_signups', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key("tournaments_signups_deck", 'tournaments_signups', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tournaments_signups_deck", 'tournaments_signups', type_='foreignkey')
    op.drop_column('tournaments_signups', 'deck_id')
    op.drop_column('tournaments', 'phase')
    op.drop_column('cards', 'in_imperium_deck')
    op.drop_column('cards', 'in_development_deck')
    op.drop_table('deck_cards')
    op.drop_table('decks')
    # ### end Alembic commands ###
