"""empty message

Revision ID: c899fcc20fe3
Revises: e0e5549aa364
Create Date: 2019-04-16 22:13:45.964117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c899fcc20fe3'
down_revision = 'e0e5549aa364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('sponsor_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'sponsor_description')
    # ### end Alembic commands ###
