"""empty message

Revision ID: d004fdd46834
Revises: 840ddc54e942
Create Date: 2020-01-29 10:06:27.320940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd004fdd46834'
down_revision = '840ddc54e942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conclave_rules_type'), 'conclave_rules', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conclave_rules_type'), table_name='conclave_rules')
    # ### end Alembic commands ###
