"""empty message

Revision ID: de895e87060c
Revises: b449e840fbc6
Create Date: 2020-05-28 12:27:31.434402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de895e87060c'
down_revision = 'b449e840fbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('conclave_distance', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('deck_value_target', sa.Integer(), nullable=False))
    op.drop_column('tournaments', 'conclave_triggers')
    op.drop_column('tournaments', 'conclave_triggered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('conclave_triggered', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('tournaments', sa.Column('conclave_triggers', mysql.TEXT(), nullable=True))
    op.drop_column('tournaments', 'deck_value_target')
    op.drop_column('tournaments', 'conclave_distance')
    # ### end Alembic commands ###
