"""empty message

Revision ID: e0e5549aa364
Revises: 470006fe6087
Create Date: 2019-04-16 20:20:21.301670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0e5549aa364'
down_revision = '470006fe6087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('unique_prize', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'unique_prize')
    # ### end Alembic commands ###
