"""empty message

Revision ID: e1d5821bcf50
Revises: be1d39187a0f
Create Date: 2019-05-07 19:50:11.741871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1d5821bcf50'
down_revision = 'be1d39187a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('tournament_signup_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('mixed_team', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tournament_signup_id'], ['tournaments_signups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tournaments_signups', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key("tournaments_signups_deck_key", 'tournaments_signups', 'decks', ['deck_id'], ['id'])
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    op.drop_constraint("tournaments_signups_deck_key", 'tournaments_signups', type_='foreignkey')
    op.drop_column('tournaments_signups', 'deck_id')
    op.drop_table('decks')
    # ### end Alembic commands ###
