"""empty message

Revision ID: ec56a0592252
Revises: 7c08c1236d17
Create Date: 2019-05-29 09:02:05.891203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec56a0592252'
down_revision = '7c08c1236d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('log', sa.Text(), nullable=False,server_default=sa.text("''")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'log')
    # ### end Alembic commands ###
