"""empty message

Revision ID: f7fe8c9cf8e6
Revises: ec56a0592252
Create Date: 2019-05-29 15:32:36.397888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fe8c9cf8e6'
down_revision = 'ec56a0592252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('bb2_name', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_coaches_bb2_name'), 'coaches', ['bb2_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaches_bb2_name'), table_name='coaches')
    op.drop_column('coaches', 'bb2_name')
    # ### end Alembic commands ###
